/*!
 * Protocol Module
 *
 * Binary protocol implementation for communication with Android companion app.
 * Uses protobuf over TCP with custom 7-byte header.
 */

pub mod codec;
pub mod connection;

// Re-export generated protobuf types
// Generated by build.rs into src/protocol/generated/
#[allow(clippy::all)]
pub mod pb {
    include!("generated/neuralbridge.rs");
}
